### ISSUE TITLE
Getting error - Cannot find name TimelineItem

### ISSUE THREAD

**Issue by suchetaswabhav** [callyafiune/ngx-horizontal-timeline#1]
Hi,

I downloaded the npm and declared the entries as mentioned . However, I get error 

        Cannot find name 'TimelineItem' 

when i declare it in my App.component.ts-

       items: TimelineItem[];     ---->//Error

        ngOnInit() {

    this.items.push({
      label: 'Test 1',
      icon: 'glyphicon glyphicon-adjust',
      active: true,
      title: 'Example 1',
      color: '16a085',
      command() {
        console.log('Action 1');
      }
    });
    
    this.items.push({
      label: 'Test 2',
      icon: 'fa fa-plus',
      title: 'Example 2',
      color: '2980b9',
      command() {
        console.log('Action 2');
      }
    });
  }

I even downloaded its Dependency  - npm tslib

**Comment by Atticus29** [comment]
Thank you so much for making this tool for us! Would it be possible to provide a working example of the implementation of this on stackblitz or something similar?

**Comment by callyafiune** [comment]
Live Example! txs 
https://stackblitz.com/edit/ngx-horizontal-timeline
