### ISSUE TITLE
ERROR TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by Atticus29** [callyafiune/ngx-horizontal-timeline#2]
#### Description
I attempted to implement the example horizontal timeline as described on [its ngx page](https://www.npmjs.com/package/ngx-horizontal-timeline).
I got an error about the TimelineItem type from the line, `private items: TimelineItem[];`. I assumed that the type was included in the package, so I added the import line, `import { TimelineItem } from 'ngx-horizontal-timeline';`. This removed that error. The next error was, 

> ERROR TypeError: Cannot read property 'push' of undefined

Corresponding to the line where I first try to use the `push` method on items: `this.items.push({...`

#### Screenshots
![The error in my StackBlitz implementation](https://markfisherstestbucket.s3.amazonaws.com/Screen+Shot+2019-07-26+at+4.25.56+PM.png)

#### To Reproduce
[Reproduction on StackBlitz](https://stackblitz.com/edit/angular-ayhkxh)

#### Tasks
Would it be possible to:
- [x] 1 Confirm that the `import { TimelineItem } from 'ngx-horizontal-timeline';` line is correct
- [x] 2 Provide a simple functioning example

Thanks in advance!

**Comment by kalaiyarasana** [comment]
Hi Atticus29,

Hope you are doing well... I am also facing the same issue... Did you get any solution for it?... If yes, can you please post it here... I am also getting the same error... But, no luck so far

**Comment by kalaiyarasana** [comment]
I fixed this issue... There is a syntax error in the documentation. Please use 

  items: TimelineItem[] = [];
  
   instead of 

  items: TimelineItem[];

**Comment by callyafiune** [comment]
Thanks!
I updated the documentation.
